### PR TITLE
support proxy auth headers

### LINKED ISSUE #1127: support passing proxy auth headers
**What is the feature and why do you need it**:

since https://github.com/kubernetes-client/python/blob/master/kubernetes/client/rest.py#L93 provides the ability to pass proxy url, my current code to set a http proxy for the api server looks like this
```
        config.load_kube_config(context=context)

        if need_proxy:
            configuration = Configuration()
            logging.debug('set proxy to ' + proxy)
            configuration.proxy = proxy
            v1 = client.CoreV1Api(api_client=ApiClient(configuration=configuration))
        else:
            v1 = client.CoreV1Api()

```

**Describe the solution you'd like to see**:
add another attribute in `Configuration` class to configure proxy auth headers. i.e. `Configuration.proxy_headers`

### PR DESCRIPTION
**Pull request by newly12**
fix #1127

### CODE REVIEW

**Comment by palnabarun** [comment]
Hi @newly12, for contributing to any of the Kubernetes repositories, you need to sign the [Contributor License Agreement](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement)

Can you please sign that it and ping back so that we can proceed further?

**Comment by newly12** [comment]
@palnabarun sorry for the delay. Just fixed CLA.

**Comment by newly12** [comment]
Hi @palnabarun could you please review this PR?

**Comment by micw523** [comment]
I restarted the build so that newly12 may not have to reopen a new PR. Let's see if this works...

**Comment by newly12** [comment]
Thanks guys for helping with the build issue.

**Comment by newly12** [comment]
It looks like proxy auth headers support is fixed in openAPI as well as this project. I will close this PR.
Thanks guys.

**Pull request closed without merging**
