### PR TITLE
Re-generate client for 9.0.0 release

### PR DESCRIPTION
**Pull request by roycaihw**
mostly version constant update. One bug fix in custom objects API to add an optional parameter

will update the CHANGELOG and README in master branch later

/assign @yliaog

### CODE REVIEW

**Comment by micw523** [comment]
May want to drop support for v6.0 since we're rolling out a stable version?

**Comment by yliaog** [comment]
i don't see the file custom_objects_spec.json for the bug fix

**Comment by roycaihw** [comment]
> May want to drop support for v6.0 since we're rolling out a stable version?

@micw523 updated

> i don't see the file custom_objects_spec.json for the bug fix

@yliaog the file is in the [gen repo](https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json). We use gen repo from HEAD to re-generate the client

**Pull request merged**
