### PR TITLE
[WIP] Release 12.0

### LINKED ISSUE #1052: Cut version 12.0.0 alpha for client
Kubernetes Python client v12.0.0 would track Kubernetes v1.16

### Tasks

- [x] Cut 12.0.0 snapshot branch
- [x] Upgrade openapi-generator version
- [x] Drop Python 2 support
> To be updated

### PR DESCRIPTION
**Pull request by scottilee**
Release 12.0 introduces several changes and is compatible with Kubernetes v1.16.

1. Updated the constants version
2. Generated client changes
3. Applied hotfixes
4. Updated python-base submodules
5. Updated the CHANGELOG (WORK-IN-PROGRESS)

Fixes #1052

### CODE REVIEW

**Comment by roycaihw** [comment]
It looks like this PR is still WIP (it merges the master branch to the release branch). Please let me know when you have more updates and need review

**Comment by roycaihw** [comment]
Could you also track upgrading the upstream code generator in the description?

**Comment by scottilee** [comment]
Closing this in favor of a new PR due to many merge conflicts and issues.

**Pull request closed without merging**
