### PR TITLE
updated compatibility matrix for 1.23.3 GA

### PR DESCRIPTION
**Pull request by yliaog**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
Thanks! Could you also update the CHANGELOG? 

/lgtm
/approve
/hold

**Comment by yliaog** [comment]
updated CHANGLOG

**Pull request merged**
