### PR TITLE
Fixes Setup.py error on Windows #676

### PR DESCRIPTION
**Pull request by Sai-Adarsh**
Initial CommitFixes Setup.py error on Windows, added shell script to check python environment, prints the python version, copy files from /kubernetes/base to /kubernetes/ and finally runs python setup.py install issue #676

### CODE REVIEW

**Comment by Sai-Adarsh** [comment]
@yliaog  @roycaihw @micw523 closed the previous PR on the same issue #676 , commits are squashed in this PR and changes are up-to-date.

**Comment by micw523** [comment]
Um you didn't have to close the previous PR but /lgtm

**Comment by micw523** [comment]
/lgtm
Come on, bot

**Comment by Sai-Adarsh** [comment]
@micw523 cool.

**Comment by Sai-Adarsh** [comment]
@yliaog could you approve the PR

**Pull request merged**
