### PR TITLE
Added Top Feature using metrics API

### LINKED ISSUE #1890: Does the library support "kubectl top pod" api?
Hi,
I want to using python library to get "top" info of pod, but I cannot find any example or document, does the library support it?

### PR DESCRIPTION
**Pull request by rclemsmith**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Implements the top feature using metrics api ( kubernetes top pod/node command  for python kubernetes client )

#### Which issue(s) this PR fixes:

Fixes #1890

#### Does this PR introduce a user-facing change?

```release-note
User can now get pod and node metrics using the top method implemented using the Metrics API
```

### CODE REVIEW

**Comment by rclemsmith** [comment]
@yliaog Could you kindly review this PR ?

**Comment by rclemsmith** [comment]
@yliaog Any idea why this PR is not moving forward. I can see that a test is failing, but not sure why.

**Comment by vincent-haoy** [comment]
Is there any way to get the cpu&memory usage in percentage? Thx.

**Pull request closed without merging**
