### PR TITLE
Fixing broken link to api-conventions doc

### LINKED ISSUE #1163: Dead link
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Pod.md
**Description of the issue (please include outputs or screenshots if possible)**:
In the items' description:
"List of pods. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md"
This "api-conventions.md" link can't be opened, please update it. 
Thank you!

### PR DESCRIPTION
**Pull request by MoShitrit**
Fixes #1163 

I performed a quick `sed` on all the `docs` directory to replace this:
`https://git.k8s.io/community/contributors/devel/api-conventions.md`
with this:
`https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md`

### CODE REVIEW

**Comment by yliaog** [comment]
these files are generated. please fix at the upstream.

**Comment by MoShitrit** [comment]
@yliaog Is there a document that describes where and how should I fix it?
I tried to find a doc that described it, but couldn't.

**Comment by palnabarun** [comment]
@MoShitrit No, the swagger spec that you linked is downloaded from upstream Kubernetes when the client is being generated.

When making any API changes or API documentation changes, the fix generally goes to the apitypes. Here is a PR for reference: https://github.com/kubernetes/kubernetes/pull/84810

**Comment by MoShitrit** [comment]
Closing that PR, I have a fix coming up in upstream repo for that.

**Pull request closed without merging**
