### PR TITLE
1.30.1 alpha release README and CHANGELOG

### PR DESCRIPTION
**Pull request by yliaog**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
/lgtm
/approve
Thanks!

**Comment by arcivanov** [comment]
@yliaog @roycaihw a tag is missing still. is it by design?

**Comment by yliaog** [comment]
do you mean v30.1.0a1 it is there: https://github.com/kubernetes-client/python/releases

**Comment by arcivanov** [comment]
Ah, nvm, pre-releases don't show on the front page. Sorry for the noise!

**Pull request merged**
