### PR TITLE
Avoid shadowing important built-ins in the example code

### PR DESCRIPTION
**Pull request by rafrafek**
#### What type of PR is this? cleanup(?)

/kind cleanup

#### What this PR does / why we need it:

Fixes a lot of potential issues when someone tries to use the code from the example.

Changes in naming:
- `type` to `type_`: The variable `type` is renamed to `type_`. In Python, type is a built-in name for a function that returns the type of an object. Using `type` as a variable name can shadow this built-in function, which could lead to confusion or errors in the code. Renaming it to `type_` avoids this potential issue.
- `object` to `object_`: Similarly, `object` is a built-in type in Python (for instance, `object` is the base class for all classes in Python). Using `object` as a variable name can also overshadow the built-in `object` type, which can lead to bugs or misunderstandings. Renaming it to `object_` avoids this issue.

#### Does this PR introduce a user-facing change? NONE

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
Please sign the CLA

**Comment by rafrafek** [comment]
@roycaihw done!

**Comment by rafrafek** [comment]
Bump.

/remove-lifecycle stale

**Comment by rafrafek** [comment]
Bump.

/remove-lifecycle stale

**Comment by rafrafek** [comment]
Is "cleanup" the best choice?

/kind cleanup

**Comment by rafrafek** [comment]
Still relevant

/remove-lifecycle stale

**Comment by rafrafek** [comment]
Hello @yliaog, could you take a look at this PR? I don't need to be the author, feel free to create a new PR with this change. The only reason I made this PR is because my friend copied the example code in the past and it broke his code because of shadowing the built-in `type` function.

**Comment by yliaog** [comment]
thanks for the PR.

/lgtm
/approve

**Pull request merged**
