### PR TITLE
Support travis pypi deployment

### PR DESCRIPTION
**Pull request by roycaihw**
ref: https://docs.travis-ci.com/user/deployment/pypi

Travis tooling fixed the indentation. Please review with whitespace change ignored. 

I'm not sure if we can test this locally. Once it's merged we should start tagging 10.1.0 release.

### CODE REVIEW

**Comment by palnabarun** [comment]
Adding the hold just for trying it out.

**Comment by palnabarun** [comment]
/unassign

Very strange that it assigned me when I did `/lgtm`

**Comment by micw523** [comment]
@palnabarun The bot automatically assigns you since you lgtm'ed the PR.

**Pull request merged**
