### PR TITLE
Use yaml.safe_load

### PR DESCRIPTION
**Pull request by ramnes**
See #718 for rationale.

@micw523

### CODE REVIEW

**Comment by micw523** [comment]
Could you leave the one in utils in its original form just for now? #673 will change the use of ```load``` into ```load_all``` which should be fine when it gets merged. The other two look good to me.

**Comment by ramnes** [comment]
@micw523 If you change #673 to use `safe_load_all` rather than `load_all`, then yes! Otherwise, I can just rebase on your PR when it's inside the tree.

**Comment by micw523** [comment]
@ramnes sounds good! I'll make the change in #673.

**Comment by ramnes** [comment]
@micw523 done

**Pull request merged**
