### PR TITLE
Update deployment_examples.py

### PR DESCRIPTION
**Pull request by nathanvanthof**
Fixed a typo

### CODE REVIEW

**Comment by yliaog** [comment]
please sign cla

the change looks good

**Comment by nathanvanthof** [comment]
> 
> 
> please sign cla
> 
> the change looks good

I think I did it, how can I check?

**Comment by scottilee** [comment]
Hey @nathanvanthof it looks like you still haven't signed the CLA. If you want to get your contribution in please do so: https://identity.linuxfoundation.org/projects/cncf.

**Comment by scottilee** [comment]
@nathanvanthof if you're still interested in fixing this the file has been renamed from `examples/deployment_examples.py` to `examples/deployment_crud.py`.

**Pull request closed without merging**
