### PR TITLE
Add support for using oidc  CA certificate file while refreshing token

### LINKED ISSUE #1915: Add support for idp-certificate-authority key in the oidc auth plugin
**What is the feature and why do you need it**:
Currently the OIDC auth plugin only supports `idp-certificate-authority-data` key to load CA certificates. It would be good to support specifying CA certificate file also. While managing a lot of clusters encoding the CA certificates in config file makes it a cumbersome to update.
**Describe the solution you'd like to see**:
Support for `idp-certificate-authority` key in the oidc plugin for specifying CA certificates using a file.

https://github.com/kubernetes-client/python/issues/1915#tasklist-block-66a117a2-7c0c-4a36-a1e5-6c185d46613d

### PR DESCRIPTION
**Pull request by vgupta3**
#### What this PR does / why we need it:
This PR adds support for loading CA certificates from a file in the oidc auth plugin.

#### Which issue(s) this PR fixes:

Fixes #1915

#### Special notes for your reviewer:
Unable to decide if any particular tests are needed for this.

#### Does this PR introduce a user-facing change?

```release-note
Adds support for loading CA certificates from a file using the `idp-certificate-authority` key for the oidc plugin.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
could you please add a test for the change?

**Comment by vgupta3** [comment]
@yliaog  I ave added a test case. It just verify if the token refresh works fine if only `idp-certificate-authority` key is present in the oidc config.
Please let me know if we need to add any more test cases.

**Pull request merged**
