### PR TITLE
Refactor utils

### LINKED ISSUE #1381: Move regular expression compilation to the top of the module in create_from_yaml
I was going through the codebase and was trying to understand it. I landed up at:

https://github.com/kubernetes-client/python/blob/6d64cf67d38337a6fdde1908bdadf047b7118731/kubernetes/utils/create_from_yaml.py#L142-L178

I think we can refactor this function by breaking down it into a couple of nested functions to reduce cognitive complexity and maybe distribute responsibilities.

Furthermore, I have this suggestion and would love to contribute if such a change is acceptable.

```python
upper_followed_by_lower_re = re.compile('(.)([A-Z][a-z]+)')
lower_or_num_followed_by_upper_re = re.compile('([a-z0-9])([A-Z])')

def create_from_yaml_single_item(
        k8s_client, yml_object, verbose=False, **kwargs):

    def get_version_and_group(_api_version):
        _group, _, _version = _api_version.partition("/")
        if _version == "":
            _version = group
            _group = "core"
        return _version, _group

    def clean_group(_group):
        # Take care for the case e.g. api_type is "apiextensions.k8s.io"
        # Only replace the last instance
        _group = "".join(_group.rsplit(".k8s.io", 1))
        # convert group name from DNS subdomain format to
        # python class name convention
        return "".join(word.capitalize() for word in _group.split('.'))

    def clean_kind(_kind):
        # Replace CamelCased action_type into snake_case
        _kind = upper_followed_by_lower_re.sub(r'\1_\2', _kind)
        return lower_or_num_followed_by_upper_re.sub(r'\1_\2', _kind).lower()

    def get_response(_yml_obj, _k8s_api, _kind, **_kwargs):

        def get_namespaced_response(__yml_obj, __k8s_api, __kind, **__kwargs):
            __namespace = __yml_obj["metadata"]["namespace"]
            __kwargs['namespace'] = __namespace
            return getattr(__k8s_api, "create_namespaced_{0}".format(_kind_))(
                body=__yml_obj, **__kwargs)

        def get_non_namespaced_response(__yml_obj, __k8s_apis, __kind, **__kwargs):
            __kwargs.pop('namespace', None)
            return getattr(__k8s_api, "create_{0}".format(__kind))(
                body=__yml_obj, **__kwargs)

        # Expect the user to create namespaced objects more often
        if hasattr(_k8s_api, "create_namespaced_{0}"._format(kind)):
            # Decide which namespace we are going to put the object in,
            # if any
            return get_namespaced_response(_yml_obj, _k8s_api, _kind, **_kwargs)
        return get_non_namespaced_response(_yml_obj, _k8s_api, _kind, **_kwargs)


    def display_message(_kind, _resp, *, _verbose):
        if _verbose:
            _msg = "{0} created.".format(_kind)
            if hasattr(resp, 'status'):
                _msg += " status='{0}'".format(str(_resp.status))
            print(_msg)


    version, group = get_version_and_group(yml_object['apiVersion'])
    group = clean_group(group)

    fcn_to_call = "{0}{1}Api".format(group, version.capitalize())
    k8s_api = getattr(client, fcn_to_call)(k8s_client)
    kind = clean_kind(yml_object['kind'])
    resp = get_response(yml_object, k8s_api, kind, **kwargs)
    display_message(kind, resp, _verbose=verbose)
    return resp
```
Regarding the code:
- Prefixed `_` in nested function variables so that they are there are lesser chances of facing scoping issues.
- Move the regular expression pattern to the top of the module as it can hopefully reduce execution time.

I believe a couple of other functions too can be broken down but just wanted to confirm if this is acceptable.

### PR DESCRIPTION
**Pull request by abhiabhi94**
- move regex compilation to the top of the module to enable caching.

closes #1381

### CODE REVIEW

**Comment by yliaog** [comment]
thanks for the pr

/lgtm
/approve

**Comment by abhiabhi94** [comment]
Hey @ylialog, inside the script `update-pycodestyle`, we try to reorder the imports using `isort` by using `isort -y`

https://github.com/kubernetes-client/python/blob/6d64cf67d38337a6fdde1908bdadf047b7118731/scripts/update-pycodestyle.sh#L69-L71

The argument `-y` has been deprecate for `isort` versions >=5 and is applied by default.

For older versions:
```sh
$ pip freeze -l | grep -i isort
isort==4.3.21

$ isort --help | grep -Ee '\-y'
             [-w LINE_LENGTH] [-wl WRAP_LENGTH] [-ws] [-y] [--unsafe]
  -y, --apply           Tells isort to apply changes recursively without
```

Newer version:
```sh
$ pip freeze -l | grep -i isort
isort==5.7.0
$ isort --help | grep -Ee '\-y' 
$
```

I think this has not been caught because as far as I can see, the environment the `tox` environment `update-pycodestyle` is not being run in `travis`. Is this expected behavior?

Also, if we want to a consistent style as mentioned in the contributing notes, maybe we can automate this by using a pre-commit hook that runs this particular script?

**Comment by yliaog** [comment]
closing to trigger CI
/close

**Comment by yliaog** [comment]
update-pycodestyle is used here (https://github.com/kubernetes-client/python/blob/master/.travis.yml#L28), i agree it should be applied consistently for other versions.

**Comment by abhiabhi94** [comment]
As far as i can see the continous integration builds are failing due to some inconsistencies in some files. Should I fix this?

Regarding the `pycodestyle`, if you agree to maybe should I setup a [`pre-commit`](https://github.com/pre-commit/pre-commit) hook that would run this script before the commit to help automate this process(for the developer), or provide feedback before the commit(in case there are inconsistencies)?

**Pull request merged**
