### PR TITLE
updating base for file-like config load support

### PR DESCRIPTION
**Pull request by ryphon**
Base PR success, opening PR in main client to support file like config loading.

### CODE REVIEW

**Comment by ryphon** [comment]
No explanation for port forward test failure. The changes I made would have failed much higher up in the test than this, additionally they would have failed in MANY other places if something was wrong with the python-base code.

**Comment by yliaog** [comment]
please fix Travis CI build failure

**Comment by ryphon** [comment]
@yliaog Something else is wrong with the portforward_raw test that doesn't involve this PR. The Changelog PR has a failure with this test as well, with the only changes being purely README text.

**Comment by ryphon** [comment]
Yeah... @yliaog I'm not sure which commit it was. But that portforward_raw test appears to be inconsistent.

**Pull request merged**
