### PR TITLE
fix issue when trying to build ResourceField with argument name 'self'

### PR DESCRIPTION
**Pull request by abikouo**
#### What type of PR is this?

Fixes #

#### Does this PR introduce a user-facing change?
#1715 

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
could you please add a test?

**Comment by abikouo** [comment]
> could you please add a test?

done!!

**Review by fabianvf — APPROVED** [review]
very technically breaking but only on fairly internal code (if this was go it would not be exported), so I have no issue with this at all. Thanks for the fix @abikouo !

**Comment by geoberle** [comment]
thanks @abikouo for this fix!

@yliaog, @fabianvf this fix is not part of a release yet. can i help with anything?

**Pull request merged**
