### PR TITLE
Fix typos: infomration -> information

### PR DESCRIPTION
**Pull request by huangqg**
Fix typos: infomration -> information

### CODE REVIEW

**Comment by micw523** [comment]
/lgtm cancel
Could you fix detail -> detailed too?

**Comment by huangqg** [comment]
@micw523 thanks for your remind, Done the changes.

**Comment by micw523** [comment]
/lgtm
Please squash your commits.
/cc @roycaihw

**Comment by huangqg** [comment]
> /lgtm
> Please squash your commits.
> /cc @roycaihw

squashed the commits

**Pull request merged**
