### PR TITLE
Created a namespaced_custom_object.py and added patch example

### LINKED ISSUE #1438: Improve the custom_object.py to be more specific to usage of namespaced custom resource
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/tree/master/examples

**Description of the issue (please include outputs or screenshots if possible)**:

The [examples/custom_object.py](https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py) example script can be improved by making it more specific to usage of  [kubernetes.client.CustomObjectsApi](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md) for a namespaced scope custom resource.

Following are the suggestion for improvement:
- rename the file to `namespaced_custom_object.py`
- include example usage of `patch_namespaced_custom_object` method

### PR DESCRIPTION
**Pull request by Yashks1994**
#### What type of PR is this?
/kind documentation
/kind cleanup

#### What this PR does / why we need it:
Added the example to patch to namespace custom resource and renamed the file to namespaces_custom_object.py because we are providing example to the namespaces custom objects.
#### Which issue(s) this PR fixes:

Fixes #1438

```release-note

```

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
I don't see the old example file being deleted. It's confusing to have both `custom_object.py` and `namespaced_custom_object.py` working with namespaced CRs. 

I prefer keeping the file name unchanged. We can rename the example when we have both `namespaced_custom_object.py` and `clusterscoped_custom_object.py`

**Comment by Yashks1994** [comment]
yes we will be creating a new file clusterscoped_custom_object.py in the new PR and @Priyankasaggu11929 is taking care of it.

**Comment by roycaihw** [comment]
sounds good. Let's do the rename in the new PR to make the change cleaner.

**Comment by Yashks1994** [comment]
Does the changes looks good to you, or do you suggest some improvements.

**Comment by roycaihw** [comment]
I still don't see the old example file being deleted. If we merge this PR as is we will have **three** custom object examples for **two** types of API. 

Please make this PR two commits. One for adding patch example to custom_object.py, one for renaming the file to namespaced_custom_object.py.

**Comment by Yashks1994** [comment]
Created a PR to remove the custom_object.py - https://github.com/kubernetes-client/python/pull/1440

**Pull request closed without merging**
