### PR TITLE
cherrypick CHANGELOG and README

### PR DESCRIPTION
**Pull request by yliaog**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
@yliaog The python-base submodule is being rolled back in this PR. PTAL

**Comment by yliaog** [comment]
Fixed python-base issue, PTAL

**Pull request merged**
