### PR TITLE
Remove py from test-requirements.txt

### LINKED ISSUE #2286: py dependency seems unneeded
The tests have a dependency on [py](https://github.com/kubernetes-client/python/blob/master/test-requirements.txt#L6), but I can't see anything in the code import this and the tests run successfully without it.

Also note that the `py` package is in maintenance mode and should not be required anymore by new projects.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`) 3.12
- Python client version (`pip list | grep kubernetes`) 28.1

### PR DESCRIPTION
**Pull request by jelly**
`py` is in maintenance mode and nothing in this project depends on it.

#### What type of PR is this?

Fixes #2286 

#### Does this PR introduce a user-facing change?

```release-note
Remove py from test dependencies
```

### CODE REVIEW

**Comment by yliaog** [comment]
please sign cla

**Comment by jelly** [comment]
> please sign cla

Done

**Review by anandfresh — APPROVED** [review]

**Comment by jelly** [comment]
Can this be merged?

**Pull request merged**
