### PR TITLE
Update base submodule

### PR DESCRIPTION
**Pull request by chrisayoub**
Pulls in the following PRs:
https://github.com/kubernetes-client/python-base/pull/227
https://github.com/kubernetes-client/python-base/pull/223
https://github.com/kubernetes-client/python-base/pull/226

### CODE REVIEW

**Comment by chrisayoub** [comment]
Do I need to add anything to the CHANGELOG in this PR to refer to these bug fixes?

**Comment by chrisayoub** [comment]
@yliaog I think the CI build might be broken and needs to be reconfigured for this job:
https://travis-ci.org/github/kubernetes-client/python/jobs/760546407

I closed and re-opened the PR and got the same error both times.

**Comment by yliaog** [comment]
CHANGELOG is changed in the release process, i think.

**Pull request merged**
