### PR TITLE
Travis CI: The sudo: tag is now fully deprecated in Travis

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by micw523** [comment]
Can you provide the link to the document saying sudo is deprecated for future reference please?

**Comment by cclauss** [comment]
travis-ci/docs-travis-ci-com#2095 is the PR that expunged all references to the __sudo:__ tag from Travis CI docs.

**Comment by roycaihw** [comment]
/approve

could you also send a pull to remove the sudo line in [python-base](https://github.com/kubernetes-client/python-base/blob/master/.travis.yml#L4)?

**Pull request merged**
