### PR TITLE
Add base_resource_lookup to ResourceList to avoid logging error

### LINKED ISSUE #1857: base_resource_lookup unexpected at the k8s client ResourceList init
**What happened (please include outputs or screenshots)**:
base_resource_lookup unexpected at the k8s client ResourceList init
```bash
load cache error: __init__() got an unexpected keyword argument 'base_resource_lookup'
```

**What you expected to happen**:
Gracefully move on instead of erroring out/implement functionality

**How to reproduce it (as minimally and precisely as possible)**:
Pass base_resource_lookup to ResourceList

**Anything else we need to know?**:
Originated from https://github.com/openshift/openshift-restclient-python/issues/430

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`)
- Python client version (`pip list | grep kubernetes`)

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
As seen in https://github.com/openshift/openshift-restclient-python/issues/430
We are hitting a bunch of these logging errors:
```bash
load cache error: __init__() got an unexpected keyword argument 'base_resource_lookup'
```
Which seem like they could be fixed by expecting this arg.

We might be off here so would appreciate any pointers,
but kept it simple at this point without adding the actual client request support.

Thanks @myakove for the help.
#### Which issue(s) this PR fixes:

Fixes #1857

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by akalenyu** [comment]
> /assign @fabianvf

gentle ping, let us know if we are not in the right direction

**Review by fabianvf — APPROVED** [review]

**Comment by fabianvf** [comment]
Sorry missed that, ping very much appreciated. Looks straightforward to me

**Comment by akalenyu** [comment]
> Sorry missed that, ping very much appreciated. Looks straightforward to me

Thank you :pray: 
What would be the next step? did we need lgtm instead of approve?

**Comment by fabianvf** [comment]
/lgtm

Maybe?

**Pull request merged**
