### PR TITLE
Fix #2045 Delete the duplicate line of configuration.host

### LINKED ISSUE #2045: Duplicated line of code in the 'Getting Started' section
**Link to the issue**: [python/kubernetes/README.md](https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md#getting-started)

**Description of the issue**:

Currently, the host configuration is present twice in the 'Getting Started' section

```Python
# Defining host is optional and default to http://localhost
configuration.host = "http://localhost"

# Defining host is optional and default to http://localhost
configuration.host = "http://localhost"
```

I would be more than glad to create a PR to fix this.

### PR DESCRIPTION
**Pull request by yabea**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
update doc

#### Which issue(s) this PR fixes:
Fixes #2045 

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Comment by kumiDa** [comment]
@yabea, you can find the guidelines to draft a good commit message here- https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines

**Comment by alexis974** [comment]
Any update on this ?

**Pull request closed without merging**
