### PR TITLE
Stop using deprecated urllib3 API

### LINKED ISSUE #2169: Stop using deprecated urllib3 API
**What happened (please include outputs or screenshots)**:

```
/home/arcivanov/.config/kubernator/python/20/kubernetes/client/exceptions.py:91: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
  self.headers = http_resp.getheaders()
```
  
**What you expected to happen**:
No deprecation warning

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`)
- Python client version (`pip list | grep kubernetes`)

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #2169

#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:

Stop using deprecated urllib3 API.

#### Which issue(s) this PR fixes:

Fixes #2169

#### Does this PR introduce a user-facing change?

No.

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
as the start of the file shows:

    Generated by: https://openapi-generator.tech

the file is generated, fix needs to go to the generator.

**Comment by arcivanov** [comment]
@yliaog will do, thanks!

**Comment by arcivanov** [comment]
@yliaog well, this is curious. Openapi-generator for python switched to httpx from requests in the year 2020: https://github.com/openapi-generators/openapi-python-client/blob/fe76d59a2bae07b884cca75304734762547557e1/CHANGELOG.md#020---2020-03-22

What version of the generator are we even using?

**Comment by yliaog** [comment]
export OPENAPI_GENERATOR_COMMIT="v4.3.0"


https://github.com/kubernetes-client/python/blob/19928029d29ad7e1577d2ffcad7d8e0945c42f72/scripts/update-client.sh#L25

**Comment by arcivanov** [comment]
@yliaog the version v4.3.0 is prehistoric as well (current is 7.2.0) and I feel there is a zero chance that the upstream will entertain a patch at this point in time. 

Would you be amenable to a post-generation patch file similar to this https://github.com/kubernetes-client/python/blob/19928029d29ad7e1577d2ffcad7d8e0945c42f72/scripts/update-client.sh#L75?

**Comment by arcivanov** [comment]
@yliaog this has been fixed in the later versions, namely here: https://github.com/OpenAPITools/openapi-generator/blob/a5d3fb4f601e4bced19f39cb6d82799a71531282/samples/client/echo_api/python/openapi_client/rest.py#L54

Would you entertain a patch?

**Comment by yliaog** [comment]
a patch is fine, provide comment on why is the patch, and when it can be removed.

**Pull request closed without merging**
