### PR TITLE
add examples which mainly show a way to rollout statefulset and daemo…

### LINKED ISSUE #1698: There is no example about rollout for statefulset and daemonset
**What is the feature and why do you need it**:
I find there is no example about rollout for sts and ds, this is not very convenient for people who are not good at kubernetes, but want to operate kubernetes with python. If necessary, I'd like to do some contributions

### PR DESCRIPTION
**Pull request by showjason**
#### What this PR does / why we need it:
This PR shows a way to rollout statefulset, daemonset and create headless service in kubernetes with python-client

#### Which issue(s) this PR fixes:

Fixes #1698 

#### Special notes for your reviewer:
This is my first PR for python-client, if anything wrong, please kindly let me know. I will correct it as soon as possible!

### CODE REVIEW

**Comment by yliaog** [comment]
i got the following error when running the example statefulset, i'm using python 3.9.1, kubernetes client 1.23.3

Traceback (most recent call last):
  File "/usr/local/google/home/yliao/prj/client-python/examples/ss.py", line 139, in <module>
    main()
  File "/usr/local/google/home/yliao/prj/client-python/examples/ss.py", line 121, in main
    create_stateful_set(apps_v1_api, stateful_set_obj)
  File "/usr/local/google/home/yliao/prj/client-python/examples/ss.py", line 68, in create_stateful_set
    apps_v1_api.create_namespaced_stateful_set(
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api/apps_v1_api.py", line 639, in create_namespaced_stateful_set
    return self.create_namespaced_stateful_set_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api/apps_v1_api.py", line 738, in create_namespaced_stateful_set_with_http_info
    return self.api_client.call_api(
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 192, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 264, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/api_client.py", line 641, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/models/v1_stateful_set_status.py", line 79, in __init__
    self.available_replicas = available_replicas
  File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/models/v1_stateful_set_status.py", line 119, in available_replicas
    raise ValueError("Invalid value for `available_replicas`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `available_replicas`, must not be `None`

**Comment by showjason** [comment]
> 

Hi @yliaog, is your kubernetes version lower than 1.22? `availableReplicas` is supported by kubernetes since version 1.22. I think this error is caused by version mismatch between kubernetes and kubernetes client

**Comment by yliaog** [comment]
I'm using 1.23, and as the stack trace below shows, available_replicas is supported by kubernetes, the error says the its value is not valid (None)
=========================================================
File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/models/v1_stateful_set_status.py", line 79, in init
self.available_replicas = available_replicas
File "/usr/local/google/home/yliao/prj/client-python/.release/lib/python3.9/site-packages/kubernetes-23.0.0_snapshot-py3.9.egg/kubernetes/client/models/v1_stateful_set_status.py", line 119, in available_replicas
raise ValueError("Invalid value for available_replicas, must not be None") # noqa: E501

**Comment by showjason** [comment]
Hi @yliaog, I have tried several different versions between kubernetes-client and kubernetes, only when kubernetes-client version is higher than 21.0.0(exclude 21.0.0) and kubernetes version is lower than 1.22(exclude 1.22), this exception will be raised.
Could you please check your kubernetes version by `kubectl version` again. I really think it's impossible to happen if kubernetes-client/python verison is 23.0.0 and kubernetes version is 1.23

**Comment by yliaog** [comment]
i retried it, there is no error when the kubernetes server is 1.23. i'm wondering if you could add these version requirements in the comment at the beginning of the example, so people know they need such specific versions to run these examples.

**Comment by showjason** [comment]
> i retried it, there is no error when the kubernetes server is 1.23. i'm wondering if you could add these version requirements in the comment at the beginning of the example, so people know they need such specific versions to run these examples.

Done, please check it!

**Comment by showjason** [comment]
Hi @yliaog I merge all of commits into one commit, please check it again. If there are any steps I should follow, please let me know!

**Pull request merged**
