### PR TITLE
Script has functions helping GET , UPDATE and DELETE for kind : Horiz…

### PR DESCRIPTION
**Pull request by riteshvado**
Script has functions helping GET , UPDATE and DELETE for kind : HorizontalPodAutoscaler
The class has common function for HPA referenced from core_v1_api.py with little tweaks.

#### What type of PR is this?
/kind example

#### What this PR does / why we need it:
In the client I didn't find any direct function available for interacting with HPA. 
This would be useful and eventually can be added to core API.  

#### Which issue(s) this PR fixes:

NA

#### Does this PR introduce a user-facing change?
None

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Examples

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
seems to be duplicate of pr: https://github.com/kubernetes-client/python/pull/1544

**Comment by fsduser** [comment]
> seems to be duplicate of pr: #1544
That's correct. The old one was from my personal account . This is one is from my Company's account which is where I got approval from.  Old one needs to discarded.

**Comment by fsduser** [comment]
Hi ,  I wanted to use #1544  instead of this #1542 
I am sorry for confusion . 
Looks like #1544 got close.

**Pull request closed without merging**
