### PR TITLE
fix Docs to use True instead of true

### PR DESCRIPTION
**Pull request by davegallant**
Python does not syntactically accept lowercase true. It must be True.

### CODE REVIEW

**Comment by tomplus** [comment]
These files are auto-generated by swagger-codegen...

**Comment by yliaog** [comment]
yes, please fix swagger-codegen, otherwise it will be overwritten in the next release.

**Comment by davegallant** [comment]
where is the swaggger type defined for boolean? It does not appear to be in the .mustache templates here: https://github.com/zalando/connexion#connexion

**Pull request closed without merging**
