### PR TITLE
Add to_dict method to ResourceField

### PR DESCRIPTION
**Pull request by 0xFelix**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This allows to recursively convert ResourceFields to dicts.

#### Does this PR introduce a user-facing change?

```release-note
Add to_dict method to ResourceField
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
@fabianvf Ping

**Comment by pmareke** [comment]
Sorry @0xFelix  and @roycaihw I think is good practice if you put first in the code the `to_dict` and later the `__serialize` as the first one calls the second and the code is more readable.

Great PR by the way!

**Comment by 0xFelix** [comment]
@pmareke Thanks! Can you describe this in a little more detail? I'm not sure how you would change it.

`__serialize` is called recursively on every `ResourceField` beginning with the root object. `to_dict` is starting that recursion by calling `__serialize` on the root object.

**Comment by 0xFelix** [comment]
@pmareke Sorry, got it!

**Comment by pmareke** [comment]
Great job @0xFelix !!

As you're using returns in each if you can simplify a little bit the method:
```python
def __serialize(self, field):
        if isinstance(field, ResourceField):
            return {
                k: self.__serialize(v) for k, v in field.__dict__.items()
            }
        if isinstance(field, (list, tuple)):
            return [self.__serialize(item) for item in field]
        return field
```

**Comment by 0xFelix** [comment]
@pmareke Done!

**Comment by 0xFelix** [comment]
Ping @roycaihw @pmareke

**Comment by 0xFelix** [comment]
/remove-lifecycle stale

Ping @roycaihw @pmareke

**Comment by pmareke** [comment]
> /remove-lifecycle stale
> 
> Ping @roycaihw @pmareke

Hi! My comment was just a suggestions, please @roycaihw go ahead.

**Comment by roycaihw** [comment]
/lgtm
/approve
Thank you!

**Pull request merged**
