### PR TITLE
Fix small grammatical typo for possessive "its"

### PR DESCRIPTION
**Pull request by rcjsuen**

### CODE REVIEW

**Comment by rcjsuen** [comment]
/check-cla

I have completed the CLA.

**Comment by micw523** [comment]
This file is automatically generated so you’ll need to patch upstream instead.

**Comment by rcjsuen** [comment]
@micw523 Thank you for reviewing this. From looking at the `kubernetes/kubernetes` repository, it seems like their version of the `swagger.json` file [doesn't have this problem](https://raw.githubusercontent.com/kubernetes/kubernetes/23649560c060ad6cd82da8da42302f8f7e38cf1e/api/openapi-spec/swagger.json).

I guess it's just a matter of time before the `swagger.json` file in this repository gets updated then?

**Comment by micw523** [comment]
Yes, that would be the expected result.

**Comment by roycaihw** [comment]
Yes this was fixed upstream https://github.com/kubernetes/kubernetes/pull/77781. New releases against 1.15+ swagger will include the fix

/close

**Pull request closed without merging**
