### PR TITLE
Retry API call on token expiration

### PR DESCRIPTION
**Pull request by marsewe**
doesn't fit too well to the kubernetes-client design. 
Maybe s.o. has a nicer approach to fix https://github.com/kubernetes-client/python/issues/741 .

### CODE REVIEW

**Comment by micw523** [comment]
I think this is generated by swagger-codegen

**Comment by roycaihw** [comment]
/remove-lifecycle rotten

we had something tackling similar problem https://github.com/kubernetes-client/python-base/pull/92 from a different angle, and it seems to work well so far. Maybe we can go with that pattern here as well

my main concerns:
- it's better to be consistent for different auth providers
- if we (python client) can do the refresh without throwing the exception, it's better to not bother the user with a 401
- when we do the refresh, we should persist the updated token to the kubeconfig file (I'm not sure if #92 does this)

**Comment by roycaihw** [comment]
OTOH, if we go with catching the exception and refreshing, we can patch the generated client like [this one does](https://github.com/kubernetes-client/python/blob/master/scripts/rest_client_patch.diff)

**Comment by roycaihw** [comment]
Closing due to inactivity. Please reopen as needed. 

/close

**Pull request closed without merging**
