### PR TITLE
removed submodule

### PR DESCRIPTION
**Pull request by yliaog**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
Why do we have these many (321) commits?

**Comment by yliaog** [comment]
the commits are old, they are added to preserve the commit history

**Comment by leoskyrocker** [comment]
@yliaog @roycaihw 
it's not easy to see the actual changes here.
The wrapper function is great, but it seems like there is not actual documentation around it.
I would use it if we're saying we can commit to supporting it.

I'm wondering if it is going to be likely for the wrapper function to suddenly disappear/change drastically in the upcoming versions.
Alternatively, we could update the documentation if we think it is here to stay (and stay consistent) for the foreseeable future?

**Comment by roycaihw** [comment]
@leoskyrocker From the slack thread I think you mean the behavior of `load_config` loading out-of-cluster or in-cluster kubeconfig.

The behavior was inspired by client-go. We don't plan to drop this behavior. It would be nice if we document the behavior. cc @MoShitrit

**Pull request merged**
