### PR TITLE
Long term solution for using minikube in CI

### LINKED ISSUE #793: e2e tests fail with k8s v1.14.0
As we can found here: https://github.com/kubernetes/minikube/issues/3959 minikube can't start the latest version of k8s v1.14.0. Upgrading minkube to v 1.0 will be necessary when it's been released.

### PR DESCRIPTION
**Pull request by micw523**
This fixes #793 when minikube v1.0 is released. See temporary workaround #796.
/hold

### CODE REVIEW

**Comment by tomplus** [comment]
minikube 1.0 is out :smile: 

/retest

**Comment by micw523** [comment]
@tomplus Thanks!
Looks like /retest does not work in this repo. I retriggered the tests manually.

**Pull request merged**
