### PR TITLE
Generate 19.0.0-snapshot client

### PR DESCRIPTION
**Pull request by roycaihw**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR is built on top of https://github.com/kubernetes-client/python/pull/1426. Commits generated with:
```
$ KUBERNETES_BRANCH=release-1.19 CLIENT_VERSION=19.0.0-snapshot DEVELOPMENT_STATUS="3 - Alpha" scripts/release.sh
```

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by yliaog** [comment]
better to remove commit 5e1e1fd1bea409d997bd63795380e64ea546a166, submit it in the separate PR

**Comment by roycaihw** [comment]
> better to remove commit 5e1e1fd, submit it in the separate PR

Done

**Pull request merged**
