### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alkmim**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

See https://github.com/kubernetes-client/python/issues/1668

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-client/python/issues/1668

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alkmim** [comment]
@yliaog The app is requesting access to my github account and since since this is a very small contribution (a single line in a readme.md file). I prefer not provide access to applications I am not familiar with. In my specific case, it would be too much burocracy (sign docusign documents and providing permissions, personal information, etc) for such a small contribution. 

If eventually I decide to do a significant contribution in the future, than I could sign the CLA.

Sorry for the inconvenience. Feel free to discard this PR or send this modification under another user. 

Cheers, 

Gustavo

**Comment by dims** [comment]
@alkmim i understand. thanks!

**Pull request closed without merging**
