### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by oz123**
Update the configuration for building sphinx documentation with markdown. 
Now README.md is fully rendered, and it is looking much better.

Do note, this is the first PR in a series of PRs to come. I don't want to PR to be too big,
so it does not take 3 months to merge.

This PR is a partial fix for #882.

### CODE REVIEW

**Comment by micw523** [comment]
I think the reason your build failed is probably due to out-of-date sphinx specified in the test-requirements.

**Comment by oz123** [comment]
@micw523 I didn't realize that the CI tests the docs. That is a *good* thing.
The requirements are missing a package. I will update the CI to install the correct dependencies.

**Comment by micw523** [comment]
Code lgtm. I’ll need to go render it myself to take a look though.

**Comment by oz123** [comment]
@micw523 there is an online version of the updated docs in 
https://k8s-python.readthedocs.io/en/latest/README.html.

d

Also, here what needs to be done to install the requirements correctly:
sphinx

**Comment by micw523** [comment]
LGTM. The commits should probably be squashed since our bot does not have the capability. What do you think @roycaihw?

**Comment by oz123** [comment]
> Sorry, but could you investigate why the [the contributing](https://k8s-python.readthedocs.io/en/latest/contributing.html) page is not rendered correctly on the website you've shown?

Check:

https://raw.githubusercontent.com/oz123/python/docs_update/doc/source/contributing.rst
That is easy to explain:

The file is rst, but the content is markdown (`.. include:: ../../CONTRIBUTING.md`, just dumps it to the file). Now, sphinx does the following if the filename ends  with rst it parses it as rst. So since the content is markdown isn't understood by the parser it's left as is.

That said, I can probably fix it later today.

**Comment by micw523** [comment]
Um, maybe it's just me not finding it, but what is the purpose of the ```requirements-docs``` file now?

**Comment by oz123** [comment]
> Um, maybe it's just me not finding it, but what is the purpose of the `requirements-docs` file now?

Well, it's overlapping with test-requirements.txt. However, IMHO it should be seperated. If I removed the content of requirements-docs from  test-requirements.txt it would break the CI.
I'd like to avoid a large PR, and at this stage not to remove this content but also leave requirements-docs as is as an explicit reminder to documentation contributors.
I would also like to remove those requirements from test-requirements.txt  and fix the CI pipeline in a future PR.

**Comment by micw523** [comment]
I think that the test requirements file is being checked by the ```setup.py``` file to determine which package to install. These packages inside will be installed on the VM when we run the CI. Having said that, you could make the ```setup.py``` file to look at your ```requirement-docs``` file and install the packages in there. I'm not sure if that's good practice though (?)

**Comment by oz123** [comment]
> You could make the `setup.py` file to look at your `requirement-docs` file and install the packages in there. I'm not sure if that's good practice though (?)

That would be too much magic packed in `setup.py` and is a bad thing. Some people use setup.py as a replacement for makefile or decent package build. While you can do it, IMHO it is bad. `setup.py` should take care of setting up your code to work in your python environment. Reading and compiling the docs has little to do with. Most linux packages tend also to separate this (e.g debian which separates python packages to python3-xxx and python3-xxx-doc.
I think this client should follow this practice.

**Comment by micw523** [comment]
/lgtm
Given that the doc test does almost nothing right now, I'm gonna lgtm this.

**Comment by ConscriptMR** [comment]
> @micw523 there is an online version of the updated docs in
> https://k8s-python.readthedocs.io/en/latest/README.html.
> 
> d
> 
> Also, here what needs to be done to install the requirements correctly:
> sphinx

I can't find any actual documentation on this site :(

**Pull request merged**
