### PR TITLE
Added examples for Jobs and Hooks

### PR DESCRIPTION
**Pull request by ratanboddu**
Added examples for creating a Job using Kubernetes Client, also added examples for Hooks (Pre Stop and Post Start)

### CODE REVIEW

**Comment by ratanboddu** [comment]
CLA has been completed. Please verify.

**Comment by ratanboddu** [comment]
ping @lavalamp

**Comment by scottilee** [comment]
@ratanboddu It looks like you changed all the permissions in the examples folder, could you undo that?

Also, you'll probably need to add the copyright lines like lines 1-17 here: https://github.com/kubernetes-client/python/blob/master/examples/remote_cluster.py#L1.

**Comment by ratanboddu** [comment]
I have made the changes, added a few extra examples and raised a new PR #898

**Comment by scottilee** [comment]
@ratanboddu please close this PR, thanks.

**Comment by micw523** [comment]
@scottilee 
Instead, we would prefer the author to close #898, move the examples shown on the title to this PR, and keep this PR open. It would be nice that a few examples are added at one time instead of a big chunk PR that we (mostly) don't want to take a look at.

**Comment by ratanboddu** [comment]
@roycaihw @micw523  @scottilee I've split my PR's ( have already raised one #933 ). Kindly let me know if you want me to create one PR containing all the examples instead of splitting my PR's as suggested by @roycaihw in #898

**Comment by micw523** [comment]
/hold
Conflicts and permission 644-755 changes must be resolved first

**Comment by scottilee** [comment]
@ratanboddu can you also make sure to add the copyright header (e.g., https://github.com/kubernetes-client/python-base/blob/master/hack/boilerplate/boilerplate.sh.txt) as well as try to give a more descriptive explanation of what your script is doing in the comment at the top. For example, what should be the end result of running the script and why would I run this script in a Kuberenetes cluster.

**Pull request closed without merging**
