### PR TITLE
V1Secret reference to main kubernetes documentation

### PR DESCRIPTION
**Pull request by alexInhert**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Provide better understanding of what is `type`
#### Which issue(s) this PR fixes:
Fixes: https://github.com/kubernetes-client/python/issues/1487

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alexInhert** [comment]
Not really sure what is the CLA process. I don't have the time to find out.
Feel free to re-submit it by someone who has the CLA and close this PR.

**Comment by palnabarun** [comment]
@alexInhert -- the documentation is automatically generated from the OpenAPI specification which in turn is generated from struct field comments.

The change being proposed here needs to be done in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L5811 and the next client release for that k8s version would pick up the change.

Hence, closing this PR.

/close

**Comment by palnabarun** [comment]
With regards to the CLA, it needs to be signed by every Kubernetes contributor. The instructions of which are already in the comment by the bot (https://github.com/kubernetes-client/python/pull/1488#issuecomment-855634133). 🙂

**Comment by alexInhert** [comment]
OK so @palnabarun you are taking over? :)

**Pull request closed without merging**
